apiVersion: v1
kind: Service
metadata:
  name: todo-backend
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "todo-backend"
    port: 8080
  selector:
    app: todo-backend